#!/usr/bin/env python3
"""Merge hemma_bubble_popup_shell.yaml + a device vars file into one Lovelace bubble-card YAML.

Home Assistant cannot use <<: !include (merge treats include as a scalar). Use this when you
want a generated full card to !include for a *new* device (dehumidifier keeps the card inline).

Example:
  python3 dashboards/templates/scripts/render_bubble_popup_card.py \\
    --vars dashboards/templates/includes/hemma_fan_bubble_vars.yaml \\
    -o dashboards/templates/includes/hemma_fan_bubble_popup_bubble_card.yaml

Paths are relative to the homeassistant config root (directory containing dashboards/).
"""
from __future__ import annotations

import argparse
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent.parent.parent  # .../homeassistant
INCLUDES = ROOT / "dashboards" / "templates" / "includes"


def merge_card(shell_path: Path, vars_path: Path) -> dict:
    with shell_path.open(encoding="utf-8") as f:
        shell = yaml.safe_load(f)
    if not isinstance(shell, dict):
        raise SystemExit(f"Expected mapping in {shell_path}")
    with vars_path.open(encoding="utf-8") as f:
        vars_map = yaml.safe_load(f)
    if not isinstance(vars_map, dict):
        raise SystemExit(f"Expected mapping in {vars_path}")
    return {"type": "custom:bubble-card", **shell, **vars_map}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--shell",
        type=Path,
        default=INCLUDES / "hemma_bubble_popup_shell.yaml",
        help="Shell fragment (mapping under custom:bubble-card)",
    )
    p.add_argument(
        "--vars",
        type=Path,
        required=True,
        help="Per-device keys (hash, name, entity, …)",
    )
    p.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
        help="Generated Lovelace card YAML",
    )
    args = p.parse_args()

    card = merge_card(args.shell, args.vars)
    header = (
        "# AUTO-GENERATED by dashboards/templates/scripts/render_bubble_popup_card.py\n"
        f"# Sources: {args.shell.name} + {args.vars.name}\n"
        "# Do not edit by hand; change the shell or vars file and re-run the script.\n"
    )
    dumped = yaml.dump(
        card,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=999,
    )
    args.output.write_text(header + "\n" + dumped, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
